export const PATHS = {
  Auth: "/auth",
  LoginPage: "/auth?login=true",
  SignUpPage: "/auth?sign-up=true",
  ForgotPassword: "/auth/forgot-password",
  ResetPassword: "/auth/reset-password",
  Home: "/",
  Explore: "/explore",
  Notifications: "/notifications",
  Messages: "/messages",
  Bookmarks: "/bookmarks",
  Connect: "/connect",
  Profile: "/profile",
  Tweets: "/tweets",
  ProfileFollowing: "/following",
  ProfileFollower: "/followers",
  ProfileTweetsLike: "/tweets-liked",
  ProfileTweetsSaved: "/tweets-saved",
};
