export const PATHS = {
  Auth: "/auth",
  LoginPage: "/auth?login=true",
  SignUpPage: "/auth?sign-up=true",
  ForgotPassword: "/auth/forgot-password",
  ResetPassword: "/auth/reset-password",
  Logout: "/logout",
  Home: "/",
  Following: "/following",
  Explore: "/explore",
  Notifications: "/notifications",
  Messages: "/messages",
  Bookmarks: "/tweets-saved",
  Connect: "/connect",
  Profile: "/profile",
  Tweets: "/tweets",
  ProfileFollowing: "/following",
  ProfileFollower: "/followers",
  ProfileTweetsLike: "/tweets-liked",
  ProfileTweetsSaved: "/tweets-saved",
  Settings: "/settings",
  SettingAccount: "/settings/account",
  SettingPrivacy: "/settings/privacy_and_safety",
  SettingDeactivateAccount: "/settings/deactivate_account",
  SettingFlySocialBlue: "/settings/fly_social_blue",
  SettingChangePwd: "/settings/change_password",
  SettingArchived: "/settings/archived",
  EditProfile: "/settings/account/edit_information",

  TermsOfService: "/tos",
  Privacy: "/privacy",
  CookiesPolicy: "/policy",
  Accessibility: "/accessibility",
  AdsInfo: "/ads-info",
};
