export * from "./IBaseTypes";
export * from "./IError";
export * from "./auth.interface";
export * from "./tweet.interface";
export * from "./comment.interface";
export * from "./storageTweet.interface";
export * from "./filter.interface";
export * from "./user.interface";
export * from "./conversation.interface";
